name: Liquibase Rollback

on:
  workflow_dispatch:
    inputs: 
      count:
          description: "Number of recent changesets to roll back"
          required: true
          default: ""

jobs:
  RollBackCount_1:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2
    - uses: liquibase-github-actions/rollback-count@v4.30.0
      with:
        count: "${{ github.event.inputs.count }}"
        classpath: 'jarfile/mysql-connector-j-9.1.0.jar'
        changeLogFile: 'changelog.yml'
        url: 'jdbc:mysql://34.121.133.153:3306/liquibase_test_db?user=root&password=test_db'