name: Liquibase Update

on:
  workflow_dispatch:

jobs:
  Liquibase_Update:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2
    - uses: liquibase-github-actions/update@v4.30.0
      with:
        changeLogFile: 'changelog.yml'
        url: 'jdbc:mysql://34.121.133.153:3306/liquibase_test_db?user=root&password=test_db'
        classpath: 'jarfile/mysql-connector-j-9.1.0.jar'
        